### ISSUE TITLE
Invalid asm.js: Function definition doesn't match use

### ISSUE THREAD

**Issue by atmikeguo** [DomParfitt/graphviz-react#66]
an worning on console:
<img width="803" alt="image" src="https://user-images.githubusercontent.com/111490790/192763520-81905d14-e2c1-4730-9ae5-424b1ad1515b.png">
and `viz.js?ab64:33` :
<img width="491" alt="image" src="https://user-images.githubusercontent.com/111490790/192763625-66d545c8-072b-4092-95ec-0befe5757c41.png">

**Comment by DomParfitt** [comment]
Hi @atmikeguo, I'm not quite sure what the specific ask is here.

`graphviz-react` doesn't directly load in `viz.js`, rather it's a dependency of a dependency (`d3-graphviz`). So it's likely that this warning is a bug in either `d3-graphviz` or the particular version of `viz.js` that the version of `d3-graphviz` we're using uses. We're also several versions behind the current version of `d3-graphviz`, due to a breaking change in more recent versions, so it may be that it's not something that's likely to be fixed as it would require backporting to an older version of the package.
