### ISSUE TITLE
Invalid hook call `useMemo`

### ISSUE THREAD

**Issue by atmikeguo** [DomParfitt/graphviz-react#80]
the version `1.2.1` has no this problem, however after upgrading to `1.2.2`, `1.2.3`, or `1.2.4`, the problem occurs.
<img width="738" alt="image" src="https://user-images.githubusercontent.com/111490790/194181100-949c09e0-9b83-4e9b-a67d-85d75030f93b.png">

**Comment by DomParfitt** [comment]
Hi @atmikeguo, thanks for raising this. 

I believe this is an issue because we're bundling `react` as a dependency when we shouldn't be (it should be a peer dependency). This is an oversight that's existed since day 1 but is only causing issues since we switched to a functional component using hooks. 

I should be able to get a fix out later today but in the meantime I'd suggest pinning to an earlier version as a workaround.

It would probably be worth adding some kind of testing around this to ensure releases haven't regressed.
